# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Zamrony P. Juhara
title: Software developer
email: zamronypj@yahoo.com
# email_title: Email (Email title override)
phone: +62 81 7524 1131
# phone_title: Phone (Phone title override)
website: https://zamronypj.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  zamronypj
stackoverflow_username: "5855039"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#twitter_username: zpjuhara
#linkedin_username: zamronypjuhara
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/zpj400x400.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi, my name Zamrony and I am software developer. I have experience making
    many type of applications, from desktop applications, Android mobile applications to
    web applications.

    I think of myself as someone who is self-determined and adaptable. I have the ability to take on a fast-paced role thanks to my quick learning skills. I am resourceful.

    I am also versatile and friendly and helpful to my colleagues. I like to help fellow developers in many public forums such as [answering this question in Stackoverflow](https://stackoverflow.com/questions/14054122/associate-an-object-with-marker-google-map-v2/39122553#39122553) or [this question](https://stackoverflow.com/questions/48738176/constraintlayout-how-to-align-centers-of-two-views-vertically/48738272#48738272).
    I am open-minded person. I listen to others as I believe I may be able to learn something from them.

    I started programming computer as hobbyist. On my leisure time, I create and maintain several personal software projects. Some projects are open-source project such as [Fano Framework](https://fanoframework.github.io) which is a web framework written in Free Pascal.

    I wrote two books on Android and game programming topics, [Panduan Lengkap Pemrograman Android](https://andipublisher.com/produk-panduan-lengkap-pemrograman-android) and *Pemrograman Game 3D dengan DirectX*. I published Android [applications on Google Play](https://play.google.com/store/apps/developer?id=juhara.com) to fulfill my curiosity on how to deploy and publish Android application.


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fano Framework
        link: https://fanoframework.github.io
        link_text: A Pascal web framework
        additional_links:
          - title:  Fano Framework Source Code
            icon: fab fa-github
            url: https://github.com/fanoframework/fano
        description: | # this will include new lines to allow paragraphs
          This is a web framework written in Pascal programming language. Initially,
          I started this project as a proof of concept for Pascal web framework that
          has capability to map request to a class instance that responsible for
          generating response.

          Since then, it has grown with many modern web framework features added such
          as middleware support, input validation, session management, etc.
      - layout: left
        title: Fano Framework Documentation
        link: https://fanoframework.github.io
        link_text: Documentation for Fano Framework
        additional_links:
          - title:  Fano Framework Documentation
            icon: fab fa-github
            url: https://github.com/fanoframework/fanoframework.github.io
        description: | # this will include new lines to allow paragraphs
          This is documentation for Fano Framework. I believe documentation is
          essential part of software library if you want other developer to use it.

          As Fano Framework grows in features, a single README.md documentation is no longer suffice.
          I started to realize I needed a separate project to maintain documentation for Fano Framework.
      - layout: left
        title: Fano CLI
        link: https://fanoframework.github.io
        link_text: Fano Command Line tool
        additional_links:
          - title:  Fano CLI
            icon: fab fa-github
            url: https://github.com/fanoframework/fano-cli
        description: | # this will include new lines to allow paragraphs
          This is command line tool for scaffolding Fano Framework web application.
          Fano Framework uses interfaces and class composition heavily.
          Fano Framework prefers configuration over convention. It
          requires a lot of boilerplate code to start web application project.

          Fano CLI is created to help alleviate by automating project creation, creating controller, view,
          middleware etc.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Dominopos Pte Ltd
        sub_title: Front End Developer
        caption: April 2016 - present
        link: https://dominopos.com
        description: | # this will include new lines to allow paragraphs
          I am responsible for developing Gotomalls.com.
      - layout: left
        title: PT Gatra Mega Berjangka
        sub_title: Web Developer
        caption: Dec 2005 - April 2016
        description: | # this will include new lines to allow paragraphs
          I was responsible for developing all company web applications.
      - layout: left
        title: Casperlab
        sub_title: Delphi Programmer
        caption: Dec 2002 - Sep 2005
        description: | # this will include new lines to allow paragraphs
          I developed and maintained PuzzleCreator, jigsaw puzzle game authoring software.
  - title: My Books
    layout: list
    content:
      - layout: left
        title: Panduan Lengkap Pemrograman Android
        img: /images/panduan-lengkap-pemrograman-android.jpg
        link: https://andipublisher.com/produk-panduan-lengkap-pemrograman-android
        description: | # this will include new lines to allow paragraphs
          Android programming book that explains various topics from getting started, creating basic layout view,
          store data in shared preferences and database operation with SQLite to more advanced topics such as working with
          3D graphics with OpenGL ES, custom view, working with Bluetooth etc.
      - layout: left
        title: Pemrograman Game 3D dengan DirectX
        img: /images/pemrograman-game-3d-dengan-directx.webp
        description: | # this will include new lines to allow paragraphs
          DirectX programming book that discusses from getting started with DirectX components,
          working with 3D graphics with Direct3D such as rendering 3D primitives.
          Reading game input device such keyboard, mouse, gamepad and joystick
          using DirectInput. Audio programming to play multiple sound effects and game music with DirectSound. Also
          discuss network programming with DirectPlay. Book also discusses terrain rendering and fog and shader programming.

          <a data-flickr-embed="true" data-footer="true" href="https://www.flickr.com/photos/23152947@N03/albums/72157628071944416" title="Color Plate Buku Pemrograman Game 3D dengan DirectX"><img src="https://live.staticflickr.com/6236/6321315812_df778befe1_z.jpg" width="640" height="480" alt="Color Plate Buku Pemrograman Game 3D dengan DirectX"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
theme: modern-resume-theme
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
