# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
title: Zamrony P. Juhara
name: Zamrony P. Juhara
profile_title: Software developer
email: zamronypj@yahoo.com
# email_title: Email (Email title override)
# phone: +62 81 7524 1131
# phone_title: Phone (Phone title override)
website: https://zamronypj.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  zamronypj
stackoverflow_username: "5855039"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#twitter_username: zpjuhara
linkedin_username: zamroni-permana-juhara
#xing_username: jekyll
#pinterest_username: jekyll
youtube_username: "@fanoframework"
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/zpj400x400.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi, my name is Zamrony and I am a software developer. I have experience creating many types of applications, from desktop and Android mobile applications to web applications.

    I consider myself to be self-determined and adaptable. Thanks to my quick learning skills, I am able to take on fast-paced roles. For instance, I was given the task to learn AngularJS, a framework which I had practically no experience with. In just a few weeks, I was able to keep up with the team. I am also resourceful.

    In addition, I am versatile, friendly, and helpful to my colleagues. I like to assist fellow developers in various public forums, such as [answering this question in Stackoverflow](https://stackoverflow.com/questions/14054122/associate-an-object-with-marker-google-map-v2/39122553#39122553) or [this question](https://stackoverflow.com/questions/48738176/constraintlayout-how-to-align-centers-of-two-views-vertically/48738272#48738272). 
    I am an open-minded person who listens to others because I believe I can learn something from them.

    I started programming computers as a hobbyist. During my leisure time, I create and maintain several personal software projects. Some of these projects are open-source, such as the [Fano Framework](https://fanoframework.github.io), which is a web framework written in [Free Pascal](https://freepascal.org). 
    I have also created and maintain some [PHP Composer packages](https://packagist.org?query=juhara).

    I have written two books on Android and game programming topics, [Panduan Lengkap Pemrograman Android](https://andipublisher.com/produk/detail/panduan-lengkap-pemrograman-android) and [Pemrograman Game 3D dengan DirectX](https://andipublisher.com/produk/detail/pemrograman-game-3d-dengan-directx). I have also published Android [applications on Google Play](https://play.google.com/store/apps/developer?id=juhara.com) to fulfill my curiosity about deploying and publishing Android applications.
    

    **Key Skills**:
    - Programming.
    - Code debugging.
    - Web development projects.
    - Front-end web development.
    - Mobile application development.
about_content_print: | # this will include new lines to allow paragraphs
    Goal-oriented software developer brings strong commitment to collaboration and solutions-oriented problem-solving.
    Use various tools and libraries to develop custom-crafted, customer-focused software applications.

    **Key Skills**:
    - Programming
    - Code debugging
    - Web development projects
    - Front end web development
    - Mobile app development
content:
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Brankas
        sub_title: Front End Developer
        caption: March 2022 - March 2023
        link: https://brank.as
        description: | # this will include new lines to allow paragraphs
          - I was part of Tap team which is responsible for developing and maintaining Tap application, Brankas's customer-facing Golang + Vue.js application to onboard customer onto Brankas Open Finance services easily.
          - I refactored Tap application from Golang-based template into Vue.js template with Nuxt.js
          - Developed and maintain Vue.js web UI component to meet specific requirements with particular layouts.
          - Produced web UI compatible with multiple browsers and devices.
          - Collaborated with UX/UI designers to convert UI design to Vue.js component.
          - Collaborated with QA to fix any reported bugs.
          - Employed coding practices based on commonly accepted standards to establish site layout and user interface.
          - Collaborated with Customer Support to answer any customer’s technical inquiry regarding Tap application.
          - Debugging Tap-related issues including checking production logs.
      - layout: left
        title: Dominopos Pte Ltd
        sub_title: Front End Developer
        caption: April 2016 - February 2022
        link: https://dominopos.com
        description: | # this will include new lines to allow paragraphs
          - Developed gotomalls.com application to meet specific requirements with particular layouts.
          - Produced websites compatible with multiple browsers and devices.
          - Collaborated with in-house web designers to create sleek and innovative UI design.
          - Collaborated with QA to fix any reported bugs.
          - Developed landing pages, dashboards and online applications using jQuery, AngularJS, vue.js and PHP scripting.
          - Completed full redesigns of existing websites to improve navigation, enhance visuals and strengthen search engine rankings.
          - Employed coding practices based on commonly accepted standards to establish site layout and user interface.
          - Converting mockups into usable web presence with HTML, JavaScript, AJAX and JSON data from backend API.
      - layout: left
        title: PT Gatra Mega Berjangka
        sub_title: Web Developer
        caption: Dec 2005 - April 2016
        description: | # this will include new lines to allow paragraphs
          - Developed company internal web applications to meet specific requirements with particular layouts.
          - Developed landing pages, dashboards and online applications using jQuery and PHP scripting.
          - Generated web hosting presence to accommodate specified needs, uploading and maintaining files on account.
          - Worked with content creator to update web presence with current foreign exchange trading data.
      - layout: left
        title: Casperlab
        sub_title: Delphi Programmer
        caption: Dec 2002 - Sep 2005
        description: | # this will include new lines to allow paragraphs
          - Developed and maintained PuzzleCreator a puzzle game authoring programs using Delphi programming language.
          - Debugged problems caused by hardware, operating systems software, application programs.
  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fano Framework
        link: https://fanoframework.github.io
        link_text: A Pascal web framework
        additional_links:
          - title:  Fano Framework Source Code
            icon: fab fa-github
            url: https://github.com/fanoframework/fano
        description: | # this will include new lines to allow paragraphs
          This is a web framework written in Pascal programming language. Initially,
          I started this project as a proof of concept for Pascal web framework that
          has capability to map request to a class instance that responsible for
          generating response.

          Since then, it has grown with many modern web framework features added such
          as middleware support, input validation, session management, etc.
      - layout: left
        title: Fano Framework Documentation
        link: https://fanoframework.github.io
        link_text: Documentation for Fano Framework
        additional_links:
          - title:  Fano Framework Documentation
            icon: fab fa-github
            url: https://github.com/fanoframework/fanoframework.github.io
        description: | # this will include new lines to allow paragraphs
          This is documentation for Fano Framework. I believe documentation is
          essential part of software library if you want other developer to use it.

          As Fano Framework grows in features, a single README.md documentation is no longer suffice.
          I started to realize I needed a separate project to maintain documentation for Fano Framework.
      - layout: left
        title: Fano CLI
        link: https://fanoframework.github.io
        link_text: Fano Command Line tool
        additional_links:
          - title:  Fano CLI
            icon: fab fa-github
            url: https://github.com/fanoframework/fano-cli
        description: | # this will include new lines to allow paragraphs
          This is command line tool for scaffolding Fano Framework web application.
          Fano Framework uses interfaces and class composition heavily.
          Fano Framework prefers configuration over convention. It
          requires a lot of boilerplate code to start web application project.

          Fano CLI is created to alleviate problem by automating project creation, creating controller, view,
          middleware etc.
      - layout: left
        title: mod_pascal
        link: https://zamronypj.github.io/mod_pascal/
        link_text: Apache module with capability to execute Pascal program
        additional_links:
          - title:  mod_pascal
            icon: fab fa-github
            url: https://github.com/zamronypj/mod_pascal
        description: | # this will include new lines to allow paragraphs
          An Apache module with capability to execute Pascal program.
          This is inspired by mod_php or mod_python. This is proof of concept and not ready for production setup.
  - title: My Books
    layout: list
    content:
      - layout: left
        title: Panduan Lengkap Pemrograman Android
        img: /images/panduan-lengkap-pemrograman-android.jpg
        link: https://andipublisher.com/produk/detail/panduan-lengkap-pemrograman-android
        description: | # this will include new lines to allow paragraphs
          Android programming book that explains various topics from getting started, creating basic layout view,
          store data in shared preferences and database operation with SQLite to more advanced topics such as working with
          3D graphics with OpenGL ES, custom view, working with Bluetooth etc.
      - layout: left
        title: Pemrograman Game 3D dengan DirectX
        img: /images/pemrograman-game-3d-dengan-directx.webp
        link: https://andipublisher.com/produk/detail/pemrograman-game-3d-dengan-directx
        description: | # this will include new lines to allow paragraphs
          DirectX programming book that discusses from getting started with DirectX components,
          working with 3D graphics with Direct3D such as rendering 3D primitives.
          Reading game input device such keyboard, mouse, gamepad and joystick
          using DirectInput. Audio programming to play multiple sound effects and game music with DirectSound. Also
          discuss network programming with DirectPlay. Book also discusses terrain rendering and fog and shader programming.

          <p class="no-print">Images below shows what kind of 3D graphics demo applications built.

          <a data-flickr-embed="true" data-footer="true" href="https://www.flickr.com/photos/23152947@N03/albums/72157628071944416" title="Color Plate Buku Pemrograman Game 3D dengan DirectX"><img src="https://live.staticflickr.com/6236/6321315812_df778befe1_z.jpg" width="640" height="480" alt="Color Plate Buku Pemrograman Game 3D dengan DirectX"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>
          </p>
  - title: Education
    layout: list
    content:
      - layout: left
        title: Institut Teknologi Sepuluh Nopember Surabaya
        sub_title: Bachelor of Engineering
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
